In [1]:
import pandas as pd

In [2]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'],
index=[1,7,10,30]
)
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [3]:
pd.Series(['Navas','Mbappe','Neymar','Messi'])

0     Navas
1    Mbappe
2    Neymar
3     Messi
dtype: object

In [4]:
dict = {1:'Navas',7:'Mbappe',10:'Neymar',30:'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [5]:
psg_players[7]

'Mbappe'

In [6]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'])
psg_players[0:3]

0     Navas
1    Mbappe
2    Neymar
dtype: object

In [8]:
dict = {'Jugador':['Navas','Mbappe','Neymar','Messi'],
'Altura':[183.0,170.0,170.0,165.0],
'Goles':[2,200,200,200]
}
pd.DataFrame(dict,index=[1,7,10,30])

   Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    200
30   Messi   165.0    200

In [10]:
df_Players = pd.DataFrame(dict)
df_Players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [11]:
df_Players.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
df_Players

  Jugador  Altura  Goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    200